name: build and deploy

on:
  push:
    branches: [ main ]
    paths: .github/workflows/azure-kubernetes-service.yaml
  pull_request:
    branches:  none # [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-deploy-aks:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: venky2821 # name of Docker Hub ID
      IMAGE_NAME: kubernetesimage
      IMAGE_TAG: ${{ github.run_number }} # $GITHUB_RUN_NUMBER
      
      CLUSTER_NAME: aks-venkateshrg-dev-001
      RESOURSE_GROUP: venkatesh-rg
    
    steps:

    - name: Git Checkout
      uses: actions/checkout@v2
  
    - name: Build Docker Image
      run:
        docker build -f .github/workflows/Dockerfile -t venky2821/kubernetesimage:$GITHUB_RUN_NUMBER

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD_VENKY }}" | docker login -u $DOCKER_REPOSITORY --password-stdin
  
    - name: Push Image to Docker Hub
      run:
        docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
           
    # Set the target AKS cluster.
    - name: AKS Set Context
      uses: Azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.RESOURSE_GROUP }}
    
    - name: kubernetes Deploy
      uses: Azure/k8s-deploy@v1
      with:
        manifests: |
               dep.yaml
    
    - name: Run Kube-Bench to check cluster config
      continue-on-error: true
      run: |
        kubectl apply -f https://raw.githubusercontent.com/aquasecurity/kube-bench/main/job-aks.yaml
        sleep 30s
        kubectl logs job.batch/kube-bench
        kubectl delete job.batch/kube-bench
