name: Build and deploy

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/main.yml
  pull_request:
    branches: none
  workflow_dispatch: null

jobs:
  build-deploy-aks:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: emarella
      IMAGE_NAME: kubernetesimage
      IMAGE_TAG: ${{ github.run_number }}
      CLUSTER_NAME: kubernetes-admin@kubernetes
      RESOURSE_GROUP: venkatesh-rg

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: >
          docker build myapp -t $DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_RUN_NUMBER

      - name: Login to Docker Hub
        run: >
          echo "${{ secrets.DOCKER_PASSWORD_ESWAR }}" | docker login -u
          $DOCKER_REPOSITORY --password-stdin

      - name: Push Image to Docker Hub
        run: >
          docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_RUN_NUMBER

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Deploy to Kubernetes
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          export KUBECONFIG=kubeconfig
          kubectl cluster-info
          kubectl apply -f myapp/dep.yaml

          # Install Argo CD
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
          kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'
          #kubectl port-forward svc/argocd-server -n argocd 8080:443
          
          # Retrieve initial Argo CD password
          argocd_initial_password=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
          echo "Initial Argo CD password: $argocd_initial_password"

      - name: Check Argo CD Version
        uses: clowdhaus/argo-cd-action/@main
        with:
          version: 2.6.7
          command: version
          options: --client
