name: build-and-deploy

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/main.yml

jobs:
  build-deploy-aks:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: emarella
      IMAGE_NAME: kubernetesimage
      CLUSTER_NAME: kubernetes-admin@kubernetes
      RESOURCE_GROUP: venkatesh-rg

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build myapp -t $DOCKER_REPOSITORY/$IMAGE_NAME:${{ github.run_number }}

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD_ESWAR }}" | docker login -u $DOCKER_REPOSITORY --password-stdin

      - name: Push Image to Docker Hub
        run: docker push $DOCKER_REPOSITORY/$IMAGE_NAME:${{ github.run_number }}

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Deploy Application
        run: |
          kubectl cluster-info
          kubectl apply -f myapp/dep.yaml
          kubectl get pods
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/core-install.yaml
          kubectl -n argocd get pod
          kubectl -n argocd get svc
