name: build-and-deploy

on:
  push:
    branches: [ main ]
    paths: .github/workflows/main.yml
  pull_request:
    branches:  none # [ main ]
  workflow_dispatch:


jobs:

  build-deploy-aks:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: venky2821 # Docker Hub ID
      IMAGE_NAME: kubernetesimage
      IMAGE_TAG: ${{ github.run_number }}
      CLUSTER_NAME: kubernetes-admin@kubernetes
      RESOURCE_GROUP: venkatesh-rg 
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2
  
    - name: Build Docker Image
      run: |
        docker build -t $DOCKER_REPOSITORY/$IMAGE_NAME:${IMAGE_TAG} myapp

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD_VENKY }}" | docker login -u $DOCKER_REPOSITORY --password-stdin
  
    - name: Push Image to Docker Hub
      run: |
        docker push $DOCKER_REPOSITORY/$IMAGE_NAME:${IMAGE_TAG}
           
    - name: Deploy to Kubernetes
      uses: azure/k8s-deploy@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        namespace: default
        images: |
          $DOCKER_REPOSITORY/$IMAGE_NAME:${IMAGE_TAG}
        imagepullsecrets: | 
          my-image-pull-secret
